### ISSUE TITLE
Django 4.2/DjangoCMS 3.11 support

### ISSUE THREAD

**Issue by mogoh** [django-cms/djangocms-file#58]
If I ran `python manage.py makemigrations` after updating to Django 4.2/DjangoCMS 3.11, new migrations will be generated.

**Comment by marksweb** [comment]
Would be best with updates based on https://github.com/django-cms/djangocms-audio/pull/32

**Comment by mogoh** [comment]
Some questions:

- Are the changes in github actions/ci required?
- How do we use pyproject.toml and tox.ini? Is the usage documented? Can someone point me in the right direction?
- djangocms-audio uses some custom tool to generate test requirements. Do we need this or can we ignore it for now?

On the one hand, I understand the wish to modernize the pipeline.
On the other hand, I just want a new version with up to date migrations.
Can we decouple this a bit?

**Comment by marksweb** [comment]
@mogoh You're looking at classic maintainer vs user problems.

I want packages to be easy maintain and reliable so that when we release something, we know it's going to work. You just want it to be available and work.

In terms of the changes I've made to djangocms-audio, some are related to the way we manage packages. We look to have consistency across all our packages and to make things as easy as possible for everyone. Part of that is using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) which is why we [lint PR](https://github.com/django-cms/djangocms-audio/pull/32/files#diff-70c3a017bfdb629fd50281fe5f7ad22e29c0ddac36e7065e9dc6d4f0924104f4) titles. For linting itself we recently moved to use [ruff](https://github.com/django-cms/djangocms-audio/pull/32/files#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2) in place of `flake8` and `isort`.

Changes to the [test workflow](https://github.com/django-cms/djangocms-audio/pull/32/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88) mean that github actions just call `tox` which is what you'd do as a developer to run the test suite. So the change there is consistency between CI and development tests. Using [pre-commit](https://github.com/django-cms/djangocms-audio/pull/32/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9) ensures consistency and standards are met in all code that is committed. 

The use of [pyproject.toml](https://github.com/django-cms/djangocms-audio/pull/32/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711) has/is becoming the most common way to configure packages/tools and generally the documentation for this is in the tools that need the configuration.

The requirements [compile](https://github.com/django-cms/djangocms-audio/pull/32/files#diff-3dbff8b8666225552e15fdc22ebc926fa9a60257e42af19d37ec536c51829991) script gives us an improved way to maintain requirements for testing because it automatically generates the requirements files, with hashes. We just have to input a little info about python version and packages that are meant for the particular test setup. These also feed into the `tox` workflow for testing.

Then finally the [tox](https://github.com/django-cms/djangocms-audio/pull/32/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449) defines the tests we run and you'll see that the test env names match up to the requirements file names. This means installing the requirements for that test are as simple as;

```
[testenv]
deps =
    -r tests/requirements/{envname}.txt
```

Because that was my PR to solve your issue, I did the whole lot. But really, you could submit PRs to include the migration and the corresponding tests passing. Then we could release that.

**Comment by marksweb** [comment]
@mogoh Could you confirm the migration that was created please?

I'm unable to create a new migration using django 4.2.3.

```
djangocms-file on  overhaul [!?] via 🐍 on ☁️ 
❯ django-admin --version
4.2.3

djangocms-file on  overhaul [!?] via 🐍 on ☁️  
❯ python -m manage makemigrations djangocms_file
No changes detected in app 'djangocms_file'
```

**Comment by mogoh** [comment]
Thank you for your in depth explanation!
I am looking into it, but I might take some time.

**Comment by mogoh** [comment]
> @mogoh Could you confirm the migration that was created please?
> 
> I'm unable to create a new migration using django 4.2.3.
> 
> ```
> djangocms-file on  overhaul [!?] via 🐍 on ☁️ 
> ❯ django-admin --version
> 4.2.3
> 
> djangocms-file on  overhaul [!?] via 🐍 on ☁️  
> ❯ python -m manage makemigrations djangocms_file
> No changes detected in app 'djangocms_file'
> ```

As far as I can tell, everything is looking good.
I still don't fully understand everything, but it looks plausible.
Thank you for your work!

**Comment by marksweb** [comment]
@mogoh thanks for confirming 👍
